### ISSUE TITLE
변경된 부분

### ISSUE THREAD

**Issue by jenndph** [HamBab/hambab-server#11]
1. RestaurantServiceImpl에서 findByCategory 함수 수정하였습니다.
   (클라이언트:"중식"->DB:"중국식" 이기 때문에 equals 값 교체)

2. RestaurantController에서 findByCategory와 search 함수의 파라미터에 @PathVariable 어노테이션 추가하였습니다.

**Comment by leta-ha** [comment]
네 확인했습니다~
