### ISSUE TITLE
데이터 수집 및 가공

### ISSUE THREAD

**Issue by sohy19** [HamBab/hambab-server#2]

**Comment by leta-ha** [comment]
[서울시 식당 데이터.csv](https://github.com/HamBab/hambab-server/files/9258078/default.csv)
//테스트 데이터

**Comment by sohy19** [comment]
카테고리당 식당 데이터 최소 11개 이상 있어야 페이지네이션 가능 ! 데이터 추가 부탁드립니당

**Comment by leta-ha** [comment]
[서울시 식당 데이터.csv](https://github.com/HamBab/hambab-server/files/9258595/default.csv)
데이터 추가했습니다!

**Comment by sohy19** [comment]
까페 라고 되어 있는 데이터가 몇 개 있어서 카페로 수정했습니다.
[서울시 식당 데이터.csv](https://github.com/HamBab/hambab-server/files/9267908/default.csv)

**Comment by leta-ha** [comment]
[서울시 식당 데이터.csv](https://github.com/HamBab/hambab-server/files/9305364/default.csv)
